DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MID"	VARCHAR2(20)		NOT NULL,
	"MNIC"	VARCHAR2(20)		NOT NULL,
	"MPW"	VARCHAR2(20)		NOT NULL
);

DROP TABLE "GOODS";

CREATE TABLE "GOODS" (
	"GOID"	VARCHAR2(20)		NOT NULL,
	"GONM"	VARCHAR2(50)		NOT NULL,
	"GOTYPE_A"	VARCHAR2(10)		NOT NULL,
	"GOTYPE_B"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "GOODS"."GOTYPE_A" IS '전체메뉴';

COMMENT ON COLUMN "GOODS"."GOTYPE_B" IS '세부메뉴값';

DROP TABLE "BY_GOODS";

CREATE TABLE "BY_GOODS" (
	"GONM"	VARCHAR2(50)		NOT NULL,
	"GOPRICE"	NUMBER		NOT NULL,
	"MID"	VARCHAR2(20)		NOT NULL,
	"GOID"	VARCHAR2(20)		NOT NULL,
	"GONU"	NUMBER		NOT NULL
);

DROP TABLE "BY_REVIEW";

CREATE TABLE "BY_REVIEW" (
	"GOID"	VARCHAR2(20)		NOT NULL,
	"MID"	VARCHAR2(20)		NOT NULL,
	"RTME"	TIMESTAMP		NOT NULL,
	"RCONT"	VARCHAR2(4000)		NOT NULL,
	"RSTAR"	NUMBER(1)		NOT NULL
);

COMMENT ON COLUMN "BY_REVIEW"."RSTAR" IS '1-5점 중 선택';

DROP TABLE "BY_QNA";

CREATE TABLE "BY_QNA" (
	"GOID"	VARCHAR2(20)		NOT NULL,
	"MID"	VARCHAR2(20)		NOT NULL,
	"QTME"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"QCONT"	VARCHAR2(4000)		NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MID"
);

ALTER TABLE "GOODS" ADD CONSTRAINT "PK_GOODS" PRIMARY KEY (
	"GOID"
);

ALTER TABLE "BY_GOODS" ADD CONSTRAINT "FK_MEMBER_TO_BY_GOODS_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "BY_GOODS" ADD CONSTRAINT "FK_GOODS_TO_BY_GOODS_1" FOREIGN KEY (
	"GOID"
)
REFERENCES "GOODS" (
	"GOID"
);

ALTER TABLE "BY_REVIEW" ADD CONSTRAINT "FK_GOODS_TO_BY_REVIEW_1" FOREIGN KEY (
	"GOID"
)
REFERENCES "GOODS" (
	"GOID"
);

ALTER TABLE "BY_REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_BY_REVIEW_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "BY_QNA" ADD CONSTRAINT "FK_GOODS_TO_BY_QNA_1" FOREIGN KEY (
	"GOID"
)
REFERENCES "GOODS" (
	"GOID"
);

ALTER TABLE "BY_QNA" ADD CONSTRAINT "FK_MEMBER_TO_BY_QNA_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

