DESC "BY_GOODS";
DESC "BY_REVIEW";
DESC "BY_QNA";
DESC "MEMBER";
DESC "GOODS";

SELECT * FROM "BY_GOODS";
SELECT * FROM "BY_REVIEW";
SELECT * FROM "BY_QNA";
SELECT * FROM "MEMBER";
SELECT * FROM "GOODS";

